function w2_embed(i){function z(b,c){if(b.getElementsByClassName)return b.getElementsByClassName(c);else{for(var a=b.getElementsByTagName("*"),d=a.length,e=[];d--;)(" "+a[d].className+" ").indexOf(" "+c+" ")!=-1&&e.push(a[d]);return e.reverse()}}function F(b,c){if(u===null)u=prompt("What name would you like to post this under?","Anonymous").replace(/ /g,"+");u!=""&&m.wavelet.participant.add("anony-bot+"+u+"@appspot.com",b,c);return u}function o(b,c,a){var d=(X++).toString();if(a)x[d]=a;G.push({id:d,
method:"wave."+b,params:c});return d}function B(b){var c=document.createElement("script");c.src=(location.protocol=="https:"?"https:":"http:")+"//"+b;c.onload=function(){setTimeout(function(){try{document.body.removeChild(c)}catch(a){}},500)};document.body.appendChild(c)}function Y(b,c,a){for(var d="ucb_",e=0;e<32;e++)d+="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(Math.floor(Math.random()*62));var f=document.createElement("div");f.style.position="absolute";document.body.appendChild(f);
var g;e=document.createElement("form");window["c"+d]=function(){try{if(g.contentWindow.location=="about:blank")return}catch(p){}a()};try{g=document.createElement('<iframe id="'+d+'" name="'+d+'" onload="window.c'+d+'()">')}catch(j){g=document.createElement("iframe");g.id=g.name=d;g.onload=window["c"+d]}f.appendChild(g);e.target=d;e.action=b;e.method="POST";f.appendChild(e);for(var h in c){b=document.createElement("input");b.type="text";b.name=h;b.value=c[h];e.appendChild(b)}if(window.frames[d].name!=
d)window.frames[d].name=d;e.submit()}function Z(b,c){var a="_x"+Math.random().toString(36).substr(2);window[n][a]=function(d){c(d);delete window[n][a]};Y((location.protocol=="https:"?"https:":"http:")+"//"+i.api_root+"/rpc?jsonpost="+a,{p:b},function(){setTimeout(function(){B(i.api_root+"/rpc?jsonp="+n+"."+a+"&jsonpost="+a)},100)})}function $(b,c){if(b.length>1900)return Z(b,c);var a="_x"+Math.random().toString(36).substr(2);window[n][a]=function(d){c(d);delete window[n][a]};B(i.api_root+"/rpc?jsonp="+
n+"."+a+"&p="+encodeURIComponent(b))}function v(){if(G.length==0)return false;$(JSON.stringify(G),function(b){if(b)for(var c=0;c<b.length;c++){var a=b[c].id,d=null;if(x[a]){d=x[a](b[c]);delete x[a]}if(b[c].error&&!d){if(b[c].error.code==401){alert("Your login token has expired\n"+xhr.responseText);return location="/?force_auth=true"}alert("Error "+b[c].error.code+": "+b[c].error.message)}}});G=[]}function aa(b,c){var a={},d=[];for(var e in b.properties){if(e!="url"&&e!="author")a[e]=b.properties[e];
d.push(e)}var f=document.createElement("div");f.style.margin="10px";var g=b.properties.url;f.innerHTML="<b>gadget</b> "+g+" <br>";if(i.gadgets){load_native_gadget(a,b,c,f);return f}if(g=="http://wave-api.appspot.com/public/gadgets/areyouin/gadget.xml"){var j={y:[],n:[],m:[]};for(e in a)/:answer$/.test(e)&&j[a[e]].push(e.substr(0,e.length-7));for(var h in j){f.innerHTML+="<br><span style='color:red;font-weight:bold'>"+{m:"Maybe",y:"Yes",n:"No"}[h]+"</span><br> ";if(j[h].length==0)f.innerHTML+="(None) <br>";
for(e=0;e<j[h].length;e++)f.innerHTML+=j[h][e].replace(/@googlewave.com/g,"")+' <span style="color: gray;font-style: italic">'+(a[j[h][e]+":status"]||"")+"</span><br>"}}else if(g=="http://plus-one.appspot.com/plus-one.xml"){j=0;for(e in a)j+=parseInt(a[e]);f.innerHTML+="<br><b>Votes:</b> "+j+"/"+d.length}else if(g=="http://www.elizabethsgadgets.appspot.com/public/gadget.xml")f.innerHTML+="<br> <b>Pluses</b> ("+(a.pluses||0)+")&nbsp;&nbsp;&nbsp;&nbsp;<b>Minuses</b> ("+(a.minuses||0)+")";else if(g==
"http://pushyrobot.appspot.com/gadgets/github.xml")f.innerHTML+="<pre>"+JSON.stringify(JSON.parse(unescape(a.commit)),null,2)+"</pre>";else if(g=="http://everybodyapi.appspot.com/gadget/image/gadget.xml")f.innerHTML+='<img src="'+a.imgUrl+'" width="'+a.imgWidth+'" height="'+a.imgHeight+'">';else if(g=="http://wavepollo.appspot.com/wavepollo/com.appspot.wavepollo.client.PolloWaveGadget.gadget.xml"){h={};for(j in a)if(j.indexOf("MVOTE_")==0)if(e=j.match(/MVOTE_(.+)(OPT_.+)$/)){h[e[2]]||(h[e[2]]=[]);
h[e[2]].push(e[1])}for(j in h){f.innerHTML+="<br><span style='color:red;font-weight:bold'>"+a[j]+"</span> ("+h[j].length+")<br> ";for(e=0;e<h[j].length;e++)f.innerHTML+=h[j][e].replace(/@googlewave.com/g,"")+", "}}else if(g=="https://statusee.appspot.com/gadget/statusee.xml")f.innerHTML+="<b>Status</b> "+({notstarted:"Not started",describing:"Describing",brainstorming:"Brainstorming",inprogress:"In Progress",inreview:"In Review",pending:"Pending",testing:"Testing",completed:"Completed",rejected:"Rejected",
canceled:"Canceled"}[a.sel]||a.sel.substr(7));else if(g=="http://wave-poll.googlecode.com/svn/trunk/src/poll.xml")for(j in a){h=JSON.parse(a[j]).participants;f.innerHTML+="<br><span style='color:red;font-weight:bold'>"+j.substr(7)+"</span> ("+h.length+")<br> ";for(e=0;e<h.length;e++)f.innerHTML+=h[e].replace(/@googlewave.com/g,"")+", "}else if(g=="https://everybodyapi.appspot.com/gadget/miniroster/main.xml"){f.innerHTML+="<br><span style='color:red;font-weight:bold'>Assigned</span> ("+d.length+")<br> ";
for(j in a)f.innerHTML+=j.split("~")[3]+", "}else if(g=="http://www.nebweb.com.au/wave/likey.xml")f.innerHTML+="<br> <b>Like</b> ("+(a.likeCount||0)+")&nbsp;&nbsp;&nbsp;&nbsp;<b>Dislike</b> ("+(a.dislikeCount||0)+")";else if(i.render_state||JSON.stringify(a).length<1337){console.log("Unknown Gadget",g);f.innerHTML+="<pre>"+JSON.stringify(a,null,2)+"</pre>"}return f}function ba(b){var c=document.createElement("div");c.className="wavethread";L(b,c);return c}function ca(b){for(var c=b.content+" ",a=
{},d={},e={},f=0;f<b.annotations.length;f++){var g=b.annotations[f];if(g.name.indexOf("user/d/")==0){var j=g.value.split(","),h=g.name.substr(7);if(new Date-parseInt(j[1])<36E5)e[h]="rgb("+Math.floor(205-Math.random()*100).toString()+","+Math.floor(205-Math.random()*100).toString()+","+Math.floor(205-Math.random()*100).toString()+")"}if(a[g.range.start])a[g.range.start].push(f);else a[g.range.start]=[f];if(d[g.range.end])d[g.range.end].push(f);else d[g.range.end]=[f]}j={};var p=document.createElement("div"),
k=null,q=null,s="";for(f=0;f<c.length;f++){if(a[f]||d[f]||b.elements[f]){s&&q.appendChild(document.createTextNode(s));s="";if(b.elements[f]){h=b.elements[f];if(h.type=="INLINE_BLIP")p.appendChild(ba(h.properties.id));else if(h.type=="IMAGE"){k=document.createElement("div");k.style.border="3px dotted orange";k.style.margin="10px";k.innerHTML="&lt;<b>Wave 1.0 Attachment</b> "+h.properties.attachmentId+" "+h.properties.caption+"&gt;";p.appendChild(k)}else if(h.type=="INSTALLER"){k=document.createElement("div");
k.style.border="3px dotted orange";k.style.margin="10px";k.innerHTML="&lt;<b>Extension Installer</b> "+h.properties.manifest+"&gt;";p.appendChild(k)}else if(h.type=="ATTACHMENT"){k=document.createElement("div");k.style.margin="10px";k.innerHTML="<b>"+h.properties.mimeType+"</b> "+h.properties.caption+"<br>";if(h.properties.mimeType.indexOf("image/")==0){var t=document.createElement("img");t.src=h.properties.attachmentUrl;if(P){t.style.width="100%";t.onclick=function(){t.style.width=t.style.width.indexOf("%")==
-1?"100%":""}}k.appendChild(t)}else k.innerHTML+="<a href='"+h.properties.attachmentUrl+"'>Download</a>";p.appendChild(k)}else if(h.type=="GADGET")p.appendChild(aa(h,b));else h.type!="LINE"&&console.log("unknown element type",h.type,h.properties);k=document.createElement(h.properties.lineType||"p");if(h.properties.indent)k.style.marginLeft=h.properties.indent*20+"px";if(h.properties.alignment)k.style.textAlign={l:"left",c:"center",r:"right"}[h.properties.alignment];h.properties.direction&&k.setAttribute("dir",
{l:"ltr",r:"rtl"}[h.properties.alignment]);p.appendChild(k)}if(a[f])for(var C=a[f],D=C.length;D--;){g=b.annotations[C[D]];j[g.name]||(j[g.name]=[]);j[g.name].push(g.value);if(g.name.indexOf("user/e/")==0){h=g.name.substr(7);if(e[h]){var H=document.createElement("span");H.className="cursor";H.innerHTML=g.value.replace(/@.+/,"");H.style.backgroundColor=e[h];q.appendChild(H)}}}if(d[f]){C=d[f];for(D=C.length;D--;){g=b.annotations[C[D]];j[g.name].shift();j[g.name].length==0&&delete j[g.name]}}q=j["link/auto"]||
j["link/manual"]||j["link/wave"]?document.createElement("a"):document.createElement("span");k.appendChild(q);for(g in j){h=j[g][0];if(g.indexOf("style/")==0)q.style[g.substr(6)]=h;else if(g=="conv/title")q.style.fontWeight="bold";else if(g!="spell")if(g!="lang")if(g=="link/manual"||g=="link/auto"){q.href=h;q.target="_blank"}else if(g=="link/wave"){q.href="#wave:"+h;q.setAttribute("onclick","ch(this)")}else g.indexOf("user/e")!=0&&g.indexOf("user/d")!=0&&g.indexOf("user/r")!=0&&console.log("unrecognized annotation",
g,h)}}if(c.charAt(f)!="\n")s+=c.charAt(f)}s&&q.appendChild(document.createTextNode(s));p.onclick=function(E){E=E||window.event;E.cancelBubble=true;E.stopPropagation&&E.stopPropagation()};return p}function da(b){var c=[];for(var a in r.data.blips)c.push(r.data.blips[a]);c=c.sort(function(f,g){return f.lastModifiedTime-g.lastModifiedTime});var d=function(f){var g=L(c[f].blipId,b);if(r.data.blips[c[f].parentBlipId]&&g){var j=document.createElement("blockquote");f=r.data.blips[c[f].parentBlipId];var h=
f.contributors.join(", ").replace(/@googlewave.com/g,"")+":"+f.content;j.innerHTML=h.substr(0,140)+(h.length>140?"...":"");(function(p,k,q){p.onclick=function(){k.data.blips[q].dom.scrollIntoView()}})(j,r,f.blipId);g.insertBefore(j,g.getElementsByTagName("div")[0].nextSibling)}},e=c.length-1;(function(){for(var f=Math.max(0,e-10);e>=f;e--)d(e);f&&setTimeout(arguments.callee,0)})()}function M(b,c){var a=L(b,c),d=r.data.blips[b];if(d.childBlipIds.length>0){if(d.childBlipIds.length>1){var e=document.createElement("div");
e.className="wavethread";for(var f=1;f<d.childBlipIds.length;f++)M(d.childBlipIds[f],e);e.childNodes.length!=0&&c.appendChild(e)}M(d.childBlipIds[0],c)}return a}function I(b,c){var a=P?2:5,d=document.createElement("span");if(b.length<=a||c){d.innerHTML=b.join(", ").replace(/anony\-bot\+(.+)\@appspot\.com/,"$1").replace(/antimatter15@googlewave.com/g,"<a href='http://antimatter15.com'>antimatter15</a>").replace(/@googlewave.com/g,"");if(c){a=document.createElement("a");a.innerHTML=" (fewer)";a.href=
"javascript:void(0)";a.onclick=function(){d.parentNode.replaceChild(I(b),d);return false};d.appendChild(a)}}else{d.innerHTML=b.slice(0,a).join(", ").replace(/antimatter15@googlewave.com/g,"<a href='http://antimatter15.com'>antimatter15</a>").replace(/anony\-bot\+(.+)\@appspot\.com/,"$1").replace(/@googlewave.com/g,"");var e=document.createElement("a");e.innerHTML=" ... ("+(b.length-a)+" more)";e.href="#";e.onclick=function(){d.parentNode.replaceChild(I(b,true),d);return false};d.appendChild(e)}return d}
function Q(b,c){for(var a=b.length;a--;)c(b[a])}function L(b,c){var a=r.data.blips[b];if(!(!a||a.dom)){var d=ca(a).innerHTML,e=document.createElement("div");r.data.blips[b].dom=e;a.html=d;a.permalink=l.permalink+"/~/"+l.waveletId.split("!")[1]+"/"+a.blipId;e.className="waveblip";d={edit:"",reply:"",remove:""};A.push(a.blipId);for(var f in d)d[f]=R+f+"("+(A.length-1)+");return false";with(d)e.innerHTML=ea.replace(/\{\{(.*)\}\}/g,function(g,j){return eval(j)});Q(z(e,"contributorlist"),function(g){g.parentNode.replaceChild(I(a.contributors),
g)});c.appendChild(e);if(i.hideroot&&b==r.data.waveletData.rootBlipId)e.style.display="none";return e}}function w(b,c){b=b.replace("/","!");c=c||b.replace(/[\/!].+/,"!conv+root");x[m.robot.fetchWave(b,c)]=function(a){y=false;r=a;l=r.data.waveletData;A=[];N=[];for(var d in r.data.blips)N.push(d);l.permalink="https://wave.google.com/wave/waveref/"+l.waveId.replace("!","/");l.blips=r.data.blips;l._bliparr=N;if(i.element)i.element.style.display="";i.element.innerHTML=S(fa,J);Q(z(i.element,"participantlist"),
function(e){e.parentNode.replaceChild(I(l.participants),e)});i.body=z(i.element,"wavebody")[0];i.chronological?da(i.body):M(l.rootBlipId,i.body)}}function T(b,c){b=b.replace("/","!");c=c||b.replace(/[\/!].+/,"!conv+root");x[m.robot.fetchWave(b,c)]=function(a){a.data.waveletData.version>l.version&&y==false&&w(b,c)};v();setTimeout(function(){T(b,c)},5E3)}function S(b,c){return b.replace(/\{\{(.+?)\}\}/g,function(a,d){try{with(c)return eval(d)}catch(e){console.error(e);return d}})}function U(b,c){var a=
document.createElement("div");a.className+=" waveedit ";var d="eid"+Math.random().toString().substr(5),e=n+"."+d+".",f=null;y&&y.cancel();window[n][d]={submit:function(){f.disabled="disabled";y=false;c&&c(f.value,a)},cancel:function(){a.style.display="none";y=false}};y=window[n][d];for(var g in window[n][d])J[g]=e+g+"();return false";a.innerHTML=S(V,J);f=z(a,"wavetext")[0];f.value=b;return a}var n=i.globname||"w2_embed",P=(document.documentElement.clientWidth||innerWidth)<500,u=[];i.api_root=i.api_root||
"anony-bot.appspot.com";i.body=i.body||z(i.element,"wavebody")[0];var ea=i.body.innerHTML;i.body.innerHTML="";i.body=null;i.edit=i.edit||z(i.element,"waveedit")[0];if(i.edit){var V=i.edit.innerHTML;i.edit.parentNode.removeChild(i.edit)}else V='<textarea style="width:100%;height:130px" class="wavetext"></textarea><button onclick="{{submit}}">Submit</button> or <a href="#" onclick="{{cancel}}">cancel</a>';var fa=i.element.innerHTML;i.root_content=i.root_content||"(no content)";i.root_title=i.root_title||
"(no title)";i.tags=i.tags||[];i.identifier=i.identifier||location.pathname;u=null;var G=[],x={},X=0,m={robot:{fetchWave:function(b,c){return o("robot.fetchWave",{waveId:b,waveletId:c})},search:function(b,c,a){return o("robot.search",{query:b,index:c,numResults:a})},folderAction:function(b,c,a){return o("robot.folderAction",{waveId:c,modifyHow:b,waveletId:a})},notifyCapabilitiesHash:function(b){return o("robot.notifyCapabilitiesHash",{protocolVersion:b||"0.21"})},createWavelet:function(b,c){var a=
"TBD_"+d+"_0x"+(Math.random()*9E5).toString(16),d="googlewave.com!conv+root",e="googlewave.com!TBD_0x"+(Math.random()*9E5).toString(16);c||(c={});c.waveId=e;c.waveletId=d;c.rootBlipId=a;return o("robot.createWavelet",{waveletId:d,waveletData:{waveletId:d,waveId:e,rootBlipId:a,participants:b},waveId:e})}},wavelet:{appendBlip2:function(b,c,a){var d=F(c,a),e="TBD_googlewave.com!conv+root_0x"+(Math.random()*9E5).toString(16);return o("wavelet.appendBlip",{waveletId:a,waveId:c,blipId:e,proxyingFor:d,blipData:{waveletId:a,
blipId:e,waveId:c,content:b,parentBlipId:undefined},parentBlipId:undefined})},modifyParticipantRole:function(b,c,a,d){return o("wavelet.modifyParticipantRole",{waveletId:d,waveId:a,participantId:b,participantRole:c})},removeTag:function(b,c,a){return o("wavelet.modifyTag",{waveletId:a,waveId:c,name:b,modifyHow:"remove"})},addTag:function(b,c,a){return o("wavelet.modifyTag",{waveletId:a,waveId:c,name:b})},setTitle:function(b,c,a){return o("wavelet.setTitle",{waveletId:a,waveId:c,waveletTitle:b})},
participant:{add:function(b,c,a){return o("wavelet.participant.add",{waveId:c,waveletId:a,participantId:b})}}},document:{appendMarkup:function(b,c,a,d){return o("document.appendMarkup",{waveletId:d,waveId:a,blipId:c,content:b})},modify:function(b,c,a,d){var e=F(a,d);return o("document.modify",{waveletId:d,waveId:a,blipId:c,modifyAction:b,proxyingFor:e})},modify_range:function(b,c,a,d,e,f){var g=F(e,f);return o("document.modify",{waveletId:f,waveId:e,blipId:d,modifyAction:b,range:{start:c,end:a},proxyingFor:g})}},
blip:{"delete":function(b,c,a){return o("blip.delete",{waveletId:a,waveId:c,blipId:b})},replace:function(b,c,a,d){return m.document.modify({modifyHow:"REPLACE",values:["\n"+b]},c,a,d)},replace_range:function(b,c,a,d,e,f){return m.document.modify_range({modifyHow:"REPLACE",values:[b]},c,a,d,e,f)},insert:function(b,c,a,d){return m.document.modify({modifyHow:"INSERT",values:["\n"+b]},c,a,d)},append:function(b,c,a,d){return m.document.modify({modifyHow:"INSERT_AFTER",values:[b]},c,a,d)},createChild:function(b,
c,a,d){var e=F(c,a);return o("blip.createChild",{waveletId:a,waveId:c,blipId:b,proxyingFor:e,blipData:{waveletId:a,blipId:d,waveId:c,content:"",parentBlipId:b}})},contentCreateChild:function(b,c,a,d){var e="TBD_"+d+"_0x"+(Math.random()*9E5).toString(16);m.blip.createChild(c,a,d,e);m.blip.replace(b,e,a,d)}}},r={},l={},A=[],N=[],O="aph"+Math.random().toString(36).substr(4),R=n+"."+O+".";window[n][O]={addparticipant:function(){var b=prompt("Enter Participant ID to Add");if(b){if(b.indexOf("@")==-1)b+=
"@googlewave.com";m.wavelet.participant.add(b,l.waveId,l.waveletId);w(l.waveId);v()}},reload:function(){w(l.waveId);v()},setname:function(){u=prompt("What name would you like to post this under?","Anonymous").replace(/ /g,"+")||u},addtag:function(){var b=prompt("Add tag");if(b){m.wavelet.addTag(b,l.waveId,l.waveletId);w(l.waveId);v()}},edit:function(b){b=A[b];console.log(b);var c=0,a=r.data.blips[b];console.log(a);try{for(var d=a.annotations.length;d--;)if(current_blip.annotations[d].name=="conv/title")c=
current_blip.annotations[0].range.end}catch(e){}d=U(a.content.substr(c+1),function(f,g){if(a.content.substr(j)=="\n"+f)return g.style.display="none";var j=0,h;h=a.content.substr(j);for(var p="\n"+f,k=h.length,q=p.length,s=-1,t=-1;s++<k&&h[s]==p[s];);for(;t++<k&&h[k-t]==p[q-t];);h=[s,k-t+1,p.substring(s,q-t+1)];m.blip.replace_range(h[2],j+h[0],j+h[1],a.blipId,a.waveId,a.waveletId);w(a.waveId);v()});a.dom.parentNode.insertBefore(d,a.dom.nextSibling)},reply:function(b){var c=A[b];b=r.data.blips[c];var a=
U("",function(d){m.blip.contentCreateChild(d,c,l.waveId,l.waveletId);w(l.waveId);v()});if(b.childBlipIds.length>0)a.className+=" wavethread";b.dom.parentNode.insertBefore(a,b.dom.nextSibling)},remove:function(b){b=A[b];if(confirm("Are you sure you want to remove this blip?")){m.blip["delete"](b,l.waveId,l.waveletId);w(l.waveId);v()}}};var J={participantlist:'<span class="participantlist"></span>',contributorlist:'<span class="contributorlist"></span>'};for(var W in window[n][O])J[W]=R+W+"();return false";
var y=false;window.JSON||B(i.json_url||"http://anony-bot.appspot.com/assets/json2.mini.js");var K="cwe"+Math.random().toString(36).substr(4);window[n][K]=function(b){if(b){w(b);i.poll_updates&&setTimeout(function(){T(b)},5E3)}else{var c={};u="";x[m.robot.createWavelet(i.participants||[],c)]=function(d){B(i.api_root+"/db/op?jsonp="+n+"."+K+"&title="+encodeURIComponent(i.identifier)+"&waveid="+encodeURIComponent(d.data.waveId))};m.blip.insert(i.root_content,c.rootBlipId,c.waveId,c.waveletId);m.wavelet.setTitle(i.root_title,
c.waveId,c.waveletId);if(i.tags)for(var a=0;a<i.tags.length;a++)m.wavelet.addTag(i.tags[a],c.waveId,c.waveletId);u=null}v()};i.waveid?window[n][K](i.waveid):B(i.api_root+"/db/op?jsonp="+n+"."+K+"&title="+encodeURIComponent(i.identifier));return{config:i,reply:function(b){m.wavelet.appendBlip2(b,l.waveId,l.waveletId);w(l.waveId);v()},reload:function(){w(l.waveId);v()}}};
